tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      force-branch: wip-version-fix
      rgw_server: client.0
      git_remote: git://github.com/theanalyst/
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
