os_type: centos   # xenial valgrind buggy, see http://tracker.ceph.com/issues/18126
tasks:
- install:
    flavor: notcmalloc
- ceph:
- rgw:
    client.0:
      valgrind: [--tool=memcheck]
- s3tests:
    client.0:
      force-branch: wip-tagging
      rgw_server: client.0
      git_remote: git://github.com/theanalyst/
overrides:
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
      client:
        rgw lc debug interval: 10
